apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: { ... }
  creationTimestamp: 2020-01-22T18:41:56Z
  name: mysecret
  namespace: default
data:
  gh_bot_host: xxxxxx
  gh_bot_token: xxxxxx

